### ISSUE TITLE
missing install details and templates

### ISSUE THREAD

**Issue by damo2929** [digiaiiris/zabbix-azure-monitoring#18]
Hi 
hope am not being silly where is the pem file coming from?

what needs to be setup on the azure side to support this ?

also is there a zabbix template ?

**Comment by bulkware** [comment]
Hello

The pem-file should be either created or uploaded to the Azure Portal and the correct access rights should be configured for the certificate in order to access the monitoring API.

There is no generally available Zabbix template as far as I know. But there could be a template for each resource in Azure. So if you decide to start developing these templates, please let me know as well.
